### ISSUE TITLE
"Deprecate" Error prompts while importing

### ISSUE THREAD

**Issue by hkturtco** [glitchassassin/lackey#127]
The following message prompts while importing lackey package,
> C:\ProgramData\Anaconda\lib\site-packages\lackey\InputEmulation.py:8: Deprecatio
> nWarning: The mouse sub-library is deprecated and will be removed in future vers
> ions. Please use the standalone package `mouse`.
>   from keyboard import mouse

**Comment by glitchassassin** [comment]
Thanks for the issue, I've been meaning to get around to this.

**Comment by luciferz2012** [comment]
I fixed the problem by:
+ pip install mouse
+ replace *from keyboard import mouse* in InputEmulation.py with *import mouse*

**Comment by glitchassassin** [comment]
Hmm. The `mouse` library doesn't currently support OS X. I'll have to work on that before we can roll this out.

**Comment by RichFlickstein** [comment]
I am still observing this issue with Lackey version 0.7.3. Is this fix in the release?
I am using Windows 10, Python 3.6.5, and installed using pip.

C:\dev\QA\trunk\esign_separated_tests\venv\lib\site-packages\lackey\InputEmulation.py:8: DeprecationWarning: The mouse sub-library is deprecated and will be removed in future versions. Please use the standalone package mouse.
from keyboard import mouse

**Comment by glitchassassin** [comment]
Still an issue; I wasn't able to migrate to the `mouse` library directly due to lack of OS X support, and I never got the time to implement it. However, the message should be a harmless warning.

I don't currently have time to continue development & support of this library, but if you'd like to work on a fix, I'm happy to review and integrate PRs!

**Comment by RichFlickstein** [comment]
Thanks for the reply. Your library has been super helpful for me. It's
great being able to run my scripts fully in Python including being able to
debug them. Before this, I would have python open a new child process to
run the script and receive the exit code and continue from there. This now
is much better. Plus, I was having issues getting it to work correctly in
my Windows 10 environment. With your library I don't have any of those
problems. I will look later and see if your source code is available. I
don't think I'll be able to I fix it in a way that it worksfor the Mac OS
but I may save the source code so I can include it for my projects in the
future with the fix for this issue because I'm not concerned with the Mac
environment.

**Comment by glitchassassin** [comment]
There is an issue open on the `mouse` library for OS X support:

https://github.com/boppreh/mouse/issues/30
